version: 2.1

orbs:
  ruby: circleci/ruby@1.1.0
  node: circleci/node@2

jobs:
  test:
    working_directory: /mnt/ramdisk
    parameters:
      image-type: 
        type: string
        default: circleci/postgres:9.5-alpine
    docker:
      - image: cimg/ruby:2.7-node
      - image: << parameters.image-type >>
        environment:
          POSTGRES_USER: circleci-demo-ruby
          POSTGRES_DB: rails_blog_test
          POSTGRES_PASSWORD: ""
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: circleci-demo-ruby
      PGPASSWORD: ""
      RAILS_ENV: test
    steps:
      - run:
          command: |
            while true; do
              sleep 5
              ps auxwwf
              sudo du -sh /dev/shm/pgdata/data
              sudo du -sh /mnt/ramdisk
              echo "======"
            done
          background: true
      - checkout
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: memory increase
          command: |
            for i in `seq 1 100000`
            do
              file=$(mktemp file-XXX.txt)
              echo "$i memory increase" > $file
            done
      - run:
          command: cat /sys/fs/cgroup/memory/memory.max_usage_in_bytes
          when: always

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - test:
          image-type: circleci/postgres:9.5-alpine-ram
      
